// Answer database for server-side validation
// Maps category name -> letter -> array of valid answers

type AnswerDB = Record<string, Record<string, string[]>>;

export const ANSWERS: AnswerDB = {
  Animal: {
    A: [
      'Alligator',
      'Antelope',
      'Armadillo',
      'Alpaca',
      'Anaconda',
      'Aardvark',
      'Albatross',
      'Angelfish',
    ],
    B: [
      'Bear',
      'Buffalo',
      'Bat',
      'Beaver',
      'Bobcat',
      'Bison',
      'Baboon',
      'Barracuda',
      'Butterfly',
    ],
    C: [
      'Cat',
      'Cheetah',
      'Cobra',
      'Coyote',
      'Camel',
      'Crocodile',
      'Chinchilla',
      'Chameleon',
    ],
    D: [
      'Dog',
      'Dolphin',
      'Deer',
      'Duck',
      'Donkey',
      'Dragonfly',
      'Dingo',
      'Dove',
    ],
    E: ['Eagle', 'Elephant', 'Emu', 'Elk', 'Eel', 'Ermine', 'Echidna'],
    F: ['Fox', 'Frog', 'Falcon', 'Flamingo', 'Ferret', 'Firefly', 'Flounder'],
    G: [
      'Gorilla',
      'Giraffe',
      'Goat',
      'Gecko',
      'Gazelle',
      'Goldfish',
      'Grasshopper',
    ],
    H: [
      'Horse',
      'Hamster',
      'Hawk',
      'Hippo',
      'Hedgehog',
      'Heron',
      'Hyena',
      'Hummingbird',
    ],
    I: ['Iguana', 'Impala', 'Ibis', 'Irish Setter'],
    J: ['Jaguar', 'Jellyfish', 'Jackal', 'Jay', 'Jackrabbit'],
    K: ['Kangaroo', 'Koala', 'Kingfisher', 'Kiwi', 'Komodo Dragon'],
    L: ['Lion', 'Leopard', 'Llama', 'Lizard', 'Lobster', 'Lemur', 'Lynx'],
    M: [
      'Monkey',
      'Moose',
      'Mouse',
      'Mole',
      'Macaw',
      'Manatee',
      'Mongoose',
      'Meerkat',
    ],
    N: ['Narwhal', 'Newt', 'Nightingale', 'Numbat'],
    O: ['Owl', 'Otter', 'Octopus', 'Orangutan', 'Osprey', 'Ocelot', 'Ostrich'],
    P: [
      'Panda',
      'Penguin',
      'Parrot',
      'Python',
      'Panther',
      'Pig',
      'Porcupine',
      'Pelican',
    ],
    Q: ['Quail', 'Quokka', 'Quetzal'],
    R: ['Rabbit', 'Raccoon', 'Ram', 'Raven', 'Rhino', 'Rattlesnake', 'Rooster'],
    S: [
      'Snake',
      'Shark',
      'Squirrel',
      'Swan',
      'Salmon',
      'Scorpion',
      'Seal',
      'Spider',
      'Stingray',
    ],
    T: ['Tiger', 'Turtle', 'Toucan', 'Turkey', 'Toad', 'Termite', 'Tarantula'],
    U: ['Unicorn', 'Urchin', 'Urial'],
    V: ['Vulture', 'Viper', 'Vole'],
    W: ['Wolf', 'Whale', 'Walrus', 'Weasel', 'Woodpecker', 'Wombat', 'Wasp'],
    X: ['Xerus', 'X-ray Tetra'],
    Y: ['Yak', 'Yellowjacket'],
    Z: ['Zebra', 'Zebrafish'],
  },
  Country: {
    A: [
      'Australia',
      'Argentina',
      'Austria',
      'Afghanistan',
      'Albania',
      'Algeria',
      'Angola',
      'Armenia',
    ],
    B: [
      'Brazil',
      'Belgium',
      'Bolivia',
      'Bangladesh',
      'Bahamas',
      'Barbados',
      'Bhutan',
      'Bulgaria',
    ],
    C: [
      'Canada',
      'China',
      'Chile',
      'Colombia',
      'Cuba',
      'Croatia',
      'Cyprus',
      'Cameroon',
      'Chad',
    ],
    D: ['Denmark', 'Dominican Republic', 'Djibouti'],
    E: ['Egypt', 'Ecuador', 'Estonia', 'Ethiopia', 'El Salvador', 'England'],
    F: ['France', 'Finland', 'Fiji', 'Gambia'],
    G: [
      'Germany',
      'Greece',
      'Ghana',
      'Guatemala',
      'Georgia',
      'Grenada',
      'Guinea',
    ],
    H: ['Hungary', 'Honduras', 'Haiti', 'Hong Kong'],
    I: [
      'India',
      'Indonesia',
      'Ireland',
      'Iran',
      'Iraq',
      'Israel',
      'Italy',
      'Iceland',
    ],
    J: ['Japan', 'Jamaica', 'Jordan'],
    K: ['Kenya', 'Kazakhstan', 'Kuwait', 'Kyrgyzstan'],
    L: [
      'Lebanon',
      'Libya',
      'Lithuania',
      'Luxembourg',
      'Laos',
      'Latvia',
      'Liberia',
    ],
    M: [
      'Mexico',
      'Morocco',
      'Malaysia',
      'Mongolia',
      'Malta',
      'Madagascar',
      'Mozambique',
      'Myanmar',
    ],
    N: [
      'Nigeria',
      'Norway',
      'Nepal',
      'Netherlands',
      'New Zealand',
      'Nicaragua',
      'Namibia',
      'Niger',
    ],
    O: ['Oman'],
    P: [
      'Peru',
      'Poland',
      'Portugal',
      'Pakistan',
      'Panama',
      'Paraguay',
      'Philippines',
    ],
    Q: ['Qatar'],
    R: ['Russia', 'Romania', 'Rwanda'],
    S: [
      'Spain',
      'Sweden',
      'Switzerland',
      'Singapore',
      'Somalia',
      'Serbia',
      'Slovakia',
      'Slovenia',
      'Sudan',
      'Syria',
      'Senegal',
      'South Africa',
      'South Korea',
      'Sri Lanka',
    ],
    T: [
      'Thailand',
      'Turkey',
      'Taiwan',
      'Tanzania',
      'Tunisia',
      'Tonga',
      'Togo',
      'Trinidad',
    ],
    U: [
      'Uruguay',
      'Uganda',
      'Ukraine',
      'United Kingdom',
      'United States',
      'Uzbekistan',
    ],
    V: ['Venezuela', 'Vietnam'],
    W: ['Wales'],
    X: [],
    Y: ['Yemen'],
    Z: ['Zimbabwe', 'Zambia'],
  },
  City: {
    A: [
      'Amsterdam',
      'Athens',
      'Atlanta',
      'Auckland',
      'Austin',
      'Ankara',
      'Adelaide',
      'Amman',
    ],
    B: [
      'Berlin',
      'Boston',
      'Barcelona',
      'Bangkok',
      'Beijing',
      'Brisbane',
      'Brussels',
      'Budapest',
      'Bogota',
    ],
    C: [
      'Chicago',
      'Cairo',
      'Copenhagen',
      'Calgary',
      'Caracas',
      'Casablanca',
      'Chennai',
      'Cologne',
    ],
    D: [
      'Dubai',
      'Dublin',
      'Dallas',
      'Denver',
      'Detroit',
      'Dhaka',
      'Dresden',
      'Durban',
    ],
    E: ['Edinburgh', 'Edmonton'],
    F: ['Florence', 'Frankfurt', 'Fresno'],
    G: ['Geneva', 'Glasgow', 'Guangzhou', 'Gothenburg'],
    H: [
      'Houston',
      'Helsinki',
      'Hanoi',
      'Havana',
      'Hamburg',
      'Honolulu',
      'Hyderabad',
    ],
    I: ['Istanbul', 'Indianapolis'],
    J: ['Jakarta', 'Jerusalem', 'Johannesburg'],
    K: ['Kyoto', 'Kuala Lumpur', 'Kansas City', 'Karachi', 'Kathmandu', 'Kiev'],
    L: [
      'London',
      'Los Angeles',
      'Lisbon',
      'Lima',
      'Lyon',
      'Lagos',
      'Las Vegas',
      'Leipzig',
    ],
    M: [
      'Madrid',
      'Mumbai',
      'Melbourne',
      'Montreal',
      'Munich',
      'Moscow',
      'Manila',
      'Milan',
      'Memphis',
      'Marseille',
    ],
    N: [
      'New York',
      'Nairobi',
      'Naples',
      'Nashville',
      'New Orleans',
      'Nice',
      'Nuremberg',
    ],
    O: ['Orlando', 'Oslo', 'Osaka', 'Ottawa', 'Oxford'],
    P: [
      'Paris',
      'Prague',
      'Portland',
      'Perth',
      'Philadelphia',
      'Phoenix',
      'Porto',
      'Pune',
    ],
    Q: ['Quebec City', 'Quito'],
    R: ['Rome', 'Rio de Janeiro', 'Riyadh', 'Reykjavik', 'Rotterdam', 'Reno'],
    S: [
      'Sydney',
      'Shanghai',
      'San Francisco',
      'Seattle',
      'Seoul',
      'Singapore',
      'Stockholm',
      'Seville',
      'Salzburg',
      'Santiago',
    ],
    T: [
      'Tokyo',
      'Toronto',
      'Taipei',
      'Tel Aviv',
      'Tallinn',
      'Tampa',
      'Turin',
      'Tunis',
    ],
    U: ['Utrecht'],
    V: ['Vancouver', 'Venice', 'Vienna', 'Vilnius', 'Valencia'],
    W: ['Washington', 'Warsaw', 'Wellington', 'Winnipeg'],
    X: ['Xiamen'],
    Y: ['Yokohama'],
    Z: ['Zurich', 'Zagreb'],
  },
  Fruit: {
    A: ['Apple', 'Apricot', 'Avocado', 'Acai'],
    B: ['Banana', 'Blueberry', 'Blackberry', 'Blood Orange', 'Boysenberry'],
    C: [
      'Cherry',
      'Coconut',
      'Cantaloupe',
      'Clementine',
      'Cranberry',
      'Currant',
    ],
    D: ['Date', 'Dragonfruit', 'Durian', 'Dewberry'],
    E: ['Elderberry'],
    F: ['Fig'],
    G: ['Grape', 'Grapefruit', 'Guava', 'Gooseberry'],
    H: ['Honeydew', 'Huckleberry'],
    I: [],
    J: ['Jackfruit', 'Jujube'],
    K: ['Kiwi', 'Kumquat'],
    L: ['Lemon', 'Lime', 'Lychee', 'Lingonberry', 'Longan'],
    M: ['Mango', 'Melon', 'Mandarin', 'Mulberry'],
    N: ['Nectarine'],
    O: ['Orange', 'Olive'],
    P: [
      'Peach',
      'Pear',
      'Pineapple',
      'Plum',
      'Pomegranate',
      'Papaya',
      'Passion Fruit',
      'Persimmon',
    ],
    Q: ['Quince'],
    R: ['Raspberry', 'Rambutan'],
    S: ['Strawberry', 'Starfruit'],
    T: ['Tangerine', 'Tamarind'],
    U: ['Ugli Fruit'],
    V: [],
    W: ['Watermelon'],
    X: ['Ximenia'],
    Y: ['Yuzu'],
    Z: ['Zucchini'],
  },
  Sport: {
    A: ['Archery', 'Athletics', 'American Football', 'Aikido'],
    B: [
      'Basketball',
      'Baseball',
      'Boxing',
      'Badminton',
      'Bobsled',
      'Bowling',
      'BMX',
    ],
    C: ['Cricket', 'Cycling', 'Climbing', 'Canoeing', 'Curling', 'CrossFit'],
    D: ['Diving', 'Darts', 'Discus', 'Dodgeball'],
    E: ['Equestrian', 'Esports'],
    F: [
      'Football',
      'Fencing',
      'Figure Skating',
      'Freestyle Swimming',
      'Futsal',
    ],
    G: ['Golf', 'Gymnastics', 'Greco-Roman Wrestling'],
    H: ['Hockey', 'Handball', 'Hurdles', 'Horse Racing', 'Hiking'],
    I: ['Ice Hockey', 'Ice Skating'],
    J: ['Judo', 'Javelin', 'Jet Skiing'],
    K: ['Karate', 'Kayaking', 'Kickboxing', 'Kendo'],
    L: ['Lacrosse', 'Luge'],
    M: ['MMA', 'Marathon', 'Motocross'],
    N: ['Netball'],
    O: [],
    P: ['Polo', 'Paintball', 'Parkour', 'Powerlifting', 'Ping Pong'],
    Q: [],
    R: ['Rugby', 'Rowing', 'Rock Climbing', 'Rodeo', 'Rafting', 'Running'],
    S: [
      'Soccer',
      'Swimming',
      'Skiing',
      'Snowboarding',
      'Surfing',
      'Sailing',
      'Skateboarding',
      'Squash',
      'Softball',
      'Shot Put',
    ],
    T: [
      'Tennis',
      'Taekwondo',
      'Track',
      'Triathlon',
      'Table Tennis',
      'Trampolining',
    ],
    U: ['Ultimate Frisbee'],
    V: ['Volleyball'],
    W: [
      'Wrestling',
      'Weightlifting',
      'Water Polo',
      'Windsurfing',
      'Wakeboarding',
    ],
    X: [],
    Y: ['Yoga'],
    Z: ['Zumba'],
  },
  Movie: {
    A: [
      'Avatar',
      'Avengers',
      'Alien',
      'Amadeus',
      'Aladdin',
      'Annie',
      'Arrival',
      'Aquaman',
    ],
    B: [
      'Batman',
      'Brave',
      'Bambi',
      'Blade Runner',
      'Back to the Future',
      'Beauty and the Beast',
      'Black Panther',
    ],
    C: [
      'Cars',
      'Casablanca',
      'Coco',
      'Cinderella',
      'Coraline',
      'Captain America',
      'Cast Away',
    ],
    D: [
      'Dumbo',
      'Deadpool',
      'Django',
      'Dune',
      'Despicable Me',
      'Die Hard',
      'Doctor Strange',
    ],
    E: ['E.T.', 'Encanto', 'Elf', 'Eternals', 'Extraction'],
    F: [
      'Frozen',
      'Finding Nemo',
      'Forrest Gump',
      'Fast and Furious',
      'Fantasia',
      'Fight Club',
    ],
    G: [
      'Gladiator',
      'Ghostbusters',
      'Grease',
      'Gravity',
      'Get Out',
      'Gone Girl',
    ],
    H: ['Harry Potter', 'Hulk', 'Home Alone', 'Hugo', 'Her', 'Hacksaw Ridge'],
    I: ['Inception', 'Interstellar', 'Inside Out', 'Iron Man', 'Ice Age', 'It'],
    J: ['Jurassic Park', 'Jaws', 'Joker', 'John Wick', 'Jungle Book'],
    K: ['Kung Fu Panda', 'Kill Bill', 'King Kong', 'Knives Out'],
    L: [
      'Lion King',
      'Lord of the Rings',
      'La La Land',
      'Logan',
      'Luca',
      'Life of Pi',
    ],
    M: [
      'Moana',
      'Matrix',
      'Mulan',
      'Minions',
      'Mad Max',
      'Mission Impossible',
      'Megamind',
    ],
    N: [
      'Nemo',
      'Napoleon Dynamite',
      'Night at the Museum',
      'No Country for Old Men',
    ],
    O: ['Oppenheimer', 'Onward'],
    P: [
      'Pirates of the Caribbean',
      'Parasite',
      'Pinocchio',
      'Prometheus',
      'Psycho',
      'Pocahontas',
    ],
    Q: [],
    R: ['Ratatouille', 'Rocky', 'Rambo', 'Rapunzel', 'Rush Hour', 'Robin Hood'],
    S: [
      'Star Wars',
      'Shrek',
      'Spider-Man',
      'Superman',
      'Scarface',
      'Sonic',
      'Soul',
      'Spirited Away',
    ],
    T: [
      'Titanic',
      'Toy Story',
      'Top Gun',
      'Thor',
      'Transformers',
      'The Godfather',
      'Tangled',
    ],
    U: ['Up', 'Us', 'Unbreakable', 'Unstoppable'],
    V: ['Venom'],
    W: ['Wonder Woman', 'Wall-E', 'Wreck-It Ralph', 'Wicked', 'Whiplash'],
    X: ['X-Men'],
    Y: [],
    Z: ['Zootopia', 'Zodiac'],
  },
  'Singer or Band': {
    A: [
      'Adele',
      'Ariana Grande',
      'AC/DC',
      'Aerosmith',
      'Arctic Monkeys',
      'ABBA',
      'Alicia Keys',
    ],
    B: [
      'Beyonce',
      'Beatles',
      'Bruno Mars',
      'Billie Eilish',
      'Bon Jovi',
      'Bob Marley',
      'Black Sabbath',
    ],
    C: ['Coldplay', 'Cardi B', 'Christina Aguilera', 'Cher', 'Celine Dion'],
    D: [
      'Drake',
      'Dua Lipa',
      'Demi Lovato',
      'David Bowie',
      'Dolly Parton',
      'Daft Punk',
    ],
    E: [
      'Eminem',
      'Ed Sheeran',
      'Elton John',
      'Elvis Presley',
      'Enya',
      'Eagles',
    ],
    F: [
      'Foo Fighters',
      'Frank Sinatra',
      'Fleetwood Mac',
      'Florence and the Machine',
    ],
    G: ['Green Day', 'Gorillaz', 'Guns N Roses'],
    H: ['Harry Styles'],
    I: ['Imagine Dragons', 'Ice Cube'],
    J: [
      'Justin Bieber',
      'Jay-Z',
      'Jimi Hendrix',
      'Janet Jackson',
      'John Legend',
      'Justin Timberlake',
    ],
    K: [
      'Kanye West',
      'Katy Perry',
      'Kendrick Lamar',
      'Kelly Clarkson',
      'Khalid',
      'Kings of Leon',
    ],
    L: [
      'Lady Gaga',
      'Lizzo',
      'Lana Del Rey',
      'Led Zeppelin',
      'Lil Nas X',
      'Linkin Park',
    ],
    M: [
      'Madonna',
      'Mariah Carey',
      'Michael Jackson',
      'Metallica',
      'Miley Cyrus',
      'Muse',
    ],
    N: ['Nirvana', 'Nicki Minaj', 'Neil Young'],
    O: ['Olivia Rodrigo', 'One Direction', 'Oasis'],
    P: [
      'Pink',
      'Post Malone',
      'Prince',
      'Pearl Jam',
      'Pharrell Williams',
      'Panic at the Disco',
    ],
    Q: ['Queen', 'Quavo'],
    R: ['Rihanna', 'Rolling Stones', 'Red Hot Chili Peppers', 'Radiohead'],
    S: [
      'Shakira',
      'Sam Smith',
      'Sia',
      'Selena Gomez',
      'Snoop Dogg',
      'Stevie Wonder',
      'Sting',
    ],
    T: [
      'Taylor Swift',
      'The Weeknd',
      'Travis Scott',
      'Twenty One Pilots',
      'Tina Turner',
    ],
    U: ['U2', 'Usher'],
    V: ['Van Halen'],
    W: ['Whitney Houston', 'Wiz Khalifa'],
    X: ['XXXTentacion'],
    Y: [],
    Z: ['Zayn Malik', 'ZZ Top'],
  },
  Brand: {
    A: [
      'Apple',
      'Amazon',
      'Adidas',
      'Audi',
      'Adobe',
      'Airbnb',
      'American Express',
    ],
    B: ['BMW', 'Burger King', 'Balenciaga', 'Bose', 'Boeing', 'Burberry'],
    C: ['Coca-Cola', 'Chanel', 'Calvin Klein', 'Canon', 'Chevrolet', 'Costco'],
    D: ['Disney', 'Dell', 'Dior', 'Dominos', 'Dodge', 'Dunkin'],
    E: ['eBay', 'Estee Lauder'],
    F: ['Ferrari', 'Ford', 'Facebook', 'Fendi', 'FedEx'],
    G: ['Google', 'Gucci', 'Gap', 'General Electric', 'Gillette', 'Gatorade'],
    H: ['Honda', 'Hyundai', 'HP', 'Hermes', 'Hilton', 'H&M'],
    I: ['IKEA', 'Intel', 'IBM'],
    J: ['Jeep', 'JBL', 'Jordan'],
    K: ['KFC', 'Kia'],
    L: ['Louis Vuitton', 'Lego', 'Lexus', 'Loreal', 'Lamborghini', 'LinkedIn'],
    M: ['Mercedes', 'Microsoft', 'McDonalds', 'Marvel', 'Mastercard'],
    N: ['Nike', 'Netflix', 'Nintendo', 'Nestle', 'Nvidia'],
    O: ['Oracle', 'Oakley'],
    P: [
      'Prada',
      'Pepsi',
      'Porsche',
      'PayPal',
      'Puma',
      'Panasonic',
      'PlayStation',
    ],
    Q: ['Qualcomm'],
    R: ['Rolex', 'Ralph Lauren', 'Reebok', 'Ray-Ban', 'Red Bull'],
    S: [
      'Samsung',
      'Sony',
      'Starbucks',
      'Spotify',
      'Supreme',
      'Shell',
      'Subway',
    ],
    T: ['Tesla', 'Toyota', 'TikTok', 'Target', 'Tiffany', 'Twitter'],
    U: ['Uber', 'Under Armour', 'Uniqlo'],
    V: ['Visa', 'Versace', 'Volkswagen', 'Vans'],
    W: ['Walmart', 'WhatsApp', 'Warner Bros'],
    X: ['Xbox', 'Xerox', 'Xiaomi'],
    Y: ['YouTube', 'Yahoo', 'Yamaha'],
    Z: ['Zara', 'Zoom', 'Zillow'],
  },
  Occupation: {
    A: [
      'Accountant',
      'Architect',
      'Artist',
      'Astronaut',
      'Attorney',
      'Analyst',
      'Actor',
    ],
    B: [
      'Baker',
      'Banker',
      'Barber',
      'Bartender',
      'Biologist',
      'Blacksmith',
      'Butcher',
      'Bus Driver',
    ],
    C: [
      'Chef',
      'Carpenter',
      'Cashier',
      'Coach',
      'Counselor',
      'Chemist',
      'Comedian',
      'Captain',
    ],
    D: [
      'Doctor',
      'Dentist',
      'Designer',
      'Detective',
      'Driver',
      'Dancer',
      'Dietitian',
      'Director',
    ],
    E: ['Engineer', 'Electrician', 'Editor', 'Economist', 'Educator'],
    F: ['Farmer', 'Firefighter', 'Florist', 'Fisherman'],
    G: ['Gardener', 'Geologist', 'Graphic Designer', 'Guard'],
    H: ['Hairdresser', 'Historian'],
    I: ['Inspector', 'Interpreter', 'Instructor', 'Illustrator'],
    J: ['Janitor', 'Journalist', 'Judge', 'Jeweler'],
    K: ['Kindergarten Teacher'],
    L: ['Lawyer', 'Librarian', 'Lifeguard', 'Locksmith', 'Linguist'],
    M: [
      'Mechanic',
      'Manager',
      'Musician',
      'Midwife',
      'Mason',
      'Miner',
      'Mailman',
    ],
    N: ['Nurse', 'Navigator', 'Nutritionist'],
    O: ['Optician', 'Officer'],
    P: [
      'Pilot',
      'Plumber',
      'Programmer',
      'Professor',
      'Pharmacist',
      'Photographer',
      'Painter',
      'Paramedic',
      'Psychologist',
      'Physicist',
    ],
    Q: [],
    R: ['Receptionist', 'Reporter'],
    S: [
      'Surgeon',
      'Scientist',
      'Sailor',
      'Secretary',
      'Singer',
      'Soldier',
      'Sheriff',
    ],
    T: [
      'Teacher',
      'Translator',
      'Therapist',
      'Tailor',
      'Technician',
      'Trainer',
      'Trucker',
    ],
    U: ['Umpire', 'Usher', 'Undertaker'],
    V: ['Veterinarian', 'Violinist'],
    W: ['Waiter', 'Writer', 'Welder', 'Warden'],
    X: [],
    Y: [],
    Z: ['Zoologist', 'Zookeeper'],
  },
  Dessert: {
    A: ['Apple Pie', 'Affogato'],
    B: [
      'Brownie',
      'Baklava',
      'Banana Split',
      'Biscotti',
      'Bundt Cake',
      'Bread Pudding',
    ],
    C: [
      'Cheesecake',
      'Cupcake',
      'Cookie',
      'Churro',
      'Creme Brulee',
      'Cannoli',
      'Cobbler',
      'Carrot Cake',
    ],
    D: ['Donut', 'Danish'],
    E: ['Eclair'],
    F: ['Flan', 'Fudge', 'Fruit Tart', 'French Toast', 'Fritter'],
    G: ['Gelato', 'Gingerbread'],
    H: ['Hot Fudge Sundae'],
    I: ['Ice Cream', 'Italian Ice'],
    J: ['Jelly Roll'],
    K: ['Key Lime Pie'],
    L: ['Lemon Meringue', 'Lava Cake'],
    M: ['Macaron', 'Mousse', 'Mochi', 'Meringue', 'Muffin', 'Milkshake'],
    N: ['Napoleon'],
    O: ['Oreo'],
    P: [
      'Pudding',
      'Pie',
      'Panna Cotta',
      'Profiterole',
      'Pavlova',
      'Praline',
      'Popsicle',
    ],
    Q: [],
    R: ['Red Velvet Cake', 'Rice Pudding', 'Rum Cake'],
    S: [
      'Sundae',
      'Souffle',
      'Strudel',
      'Shortcake',
      'Sorbet',
      'Scone',
      'Swiss Roll',
    ],
    T: ['Tiramisu', 'Tart', 'Trifle', 'Truffle', 'Tres Leches', 'Torte'],
    U: ['Upside Down Cake'],
    V: ['Vanilla Pudding'],
    W: ['Waffle', 'Whipped Cream'],
    X: [],
    Y: ['Yogurt Parfait'],
    Z: ['Zabaglione'],
  },
  'Sea Animal': {
    A: ['Angelfish', 'Anchovy', 'Abalone'],
    B: ['Blue Whale', 'Barracuda', 'Beluga', 'Barnacle'],
    C: ['Clownfish', 'Crab', 'Coral', 'Cuttlefish', 'Clam'],
    D: ['Dolphin', 'Dugong'],
    E: ['Eel', 'Emperor Penguin'],
    F: ['Flounder', 'Flying Fish'],
    G: ['Grouper'],
    H: ['Hammerhead Shark', 'Horseshoe Crab', 'Hermit Crab', 'Humpback Whale'],
    I: [],
    J: ['Jellyfish'],
    K: ['Krill', 'Killer Whale'],
    L: ['Lobster', 'Lionfish'],
    M: ['Manatee', 'Manta Ray', 'Moray Eel', 'Mussel'],
    N: ['Narwhal', 'Nautilus'],
    O: ['Octopus', 'Orca', 'Oyster', 'Otter'],
    P: ['Pufferfish', 'Porpoise', 'Prawn', 'Plankton'],
    Q: [],
    R: ['Ray'],
    S: [
      'Seahorse',
      'Shark',
      'Starfish',
      'Squid',
      'Sea Turtle',
      'Seal',
      'Shrimp',
      'Stingray',
      'Swordfish',
      'Sea Lion',
      'Sea Urchin',
    ],
    T: ['Tuna', 'Turtle', 'Tiger Shark'],
    U: ['Urchin'],
    V: [],
    W: ['Whale', 'Walrus'],
    X: [],
    Y: ['Yellowfin Tuna'],
    Z: ['Zebrafish'],
  },
  Bird: {
    A: ['Albatross', 'Amazon Parrot'],
    B: ['Bald Eagle', 'Blue Jay', 'Bluebird', 'Budgie'],
    C: ['Cardinal', 'Crow', 'Cockatoo', 'Condor', 'Crane', 'Canary', 'Chicken'],
    D: ['Dove', 'Duck', 'Dodo'],
    E: ['Eagle', 'Emu', 'Egret'],
    F: ['Falcon', 'Flamingo', 'Finch'],
    G: ['Goose', 'Goldfinch', 'Grouse'],
    H: ['Hawk', 'Heron', 'Hummingbird', 'Hornbill'],
    I: ['Ibis'],
    J: ['Jay', 'Jackdaw'],
    K: ['Kingfisher', 'Kiwi', 'Kestrel'],
    L: ['Lark', 'Lovebird', 'Lorikeet'],
    M: ['Magpie', 'Macaw', 'Mockingbird'],
    N: ['Nightingale', 'Nighthawk'],
    O: ['Owl', 'Osprey', 'Oriole', 'Ostrich'],
    P: ['Parrot', 'Pelican', 'Penguin', 'Peacock', 'Pigeon', 'Puffin'],
    Q: ['Quail', 'Quetzal'],
    R: ['Robin', 'Raven', 'Roadrunner', 'Rooster'],
    S: [
      'Sparrow',
      'Swan',
      'Stork',
      'Swallow',
      'Seagull',
      'Starling',
      'Sandpiper',
    ],
    T: ['Toucan', 'Turkey', 'Tern', 'Thrush'],
    U: [],
    V: ['Vulture'],
    W: ['Woodpecker', 'Wren', 'Warbler'],
    X: [],
    Y: ['Yellowhammer'],
    Z: [],
  },
  Flower: {
    A: ['Azalea', 'Aster', 'Amaryllis', 'Anemone'],
    B: ['Bluebell', 'Buttercup', 'Begonia', 'Bird of Paradise'],
    C: ['Carnation', 'Chrysanthemum', 'Camellia', 'Crocus', 'Clover'],
    D: ['Daisy', 'Dahlia', 'Daffodil', 'Dandelion'],
    E: ['Edelweiss'],
    F: ['Freesia', 'Foxglove', 'Forget-me-not'],
    G: ['Gardenia', 'Geranium', 'Gladiolus'],
    H: ['Hyacinth', 'Hibiscus', 'Heather', 'Holly', 'Hydrangea'],
    I: ['Iris', 'Ivy'],
    J: ['Jasmine', 'Jonquil'],
    K: [],
    L: ['Lavender', 'Lily', 'Lotus', 'Lilac'],
    M: ['Magnolia', 'Marigold', 'Morning Glory'],
    N: ['Narcissus'],
    O: ['Orchid', 'Oleander'],
    P: ['Peony', 'Poppy', 'Petunia', 'Pansy', 'Primrose', 'Plumeria'],
    Q: ['Queen Anne Lace'],
    R: ['Rose', 'Ranunculus'],
    S: ['Sunflower', 'Snapdragon', 'Sweet Pea'],
    T: ['Tulip', 'Thistle'],
    U: [],
    V: ['Violet', 'Verbena'],
    W: ['Wisteria', 'Wildflower', 'Water Lily'],
    X: [],
    Y: ['Yarrow', 'Ylang Ylang'],
    Z: ['Zinnia'],
  },
  Color: {
    A: ['Aqua', 'Azure', 'Amber', 'Apricot', 'Ash'],
    B: ['Blue', 'Black', 'Beige', 'Bronze', 'Brown', 'Burgundy'],
    C: [
      'Crimson',
      'Coral',
      'Copper',
      'Charcoal',
      'Cyan',
      'Cherry',
      'Cream',
      'Champagne',
    ],
    D: ['Dark Blue'],
    E: ['Emerald', 'Ebony'],
    F: ['Fuchsia', 'Forest Green'],
    G: ['Green', 'Gold', 'Gray', 'Garnet'],
    H: ['Hot Pink'],
    I: ['Indigo', 'Ivory'],
    J: ['Jade'],
    K: ['Khaki'],
    L: ['Lavender', 'Lime', 'Lilac'],
    M: ['Magenta', 'Maroon', 'Mint', 'Mauve', 'Mustard'],
    N: ['Navy'],
    O: ['Orange', 'Olive', 'Onyx'],
    P: ['Purple', 'Pink', 'Peach', 'Periwinkle', 'Plum', 'Pearl'],
    Q: [],
    R: ['Red', 'Rose', 'Ruby', 'Rust'],
    S: ['Silver', 'Scarlet', 'Sapphire', 'Salmon', 'Sage', 'Sand', 'Sky Blue'],
    T: ['Teal', 'Turquoise', 'Tan', 'Taupe'],
    U: ['Umber', 'Ultramarine'],
    V: ['Violet', 'Vermillion'],
    W: ['White', 'Wine'],
    X: [],
    Y: ['Yellow'],
    Z: [],
  },
  Vegetable: {
    A: ['Artichoke', 'Asparagus', 'Arugula'],
    B: [
      'Broccoli',
      'Brussels Sprouts',
      'Beet',
      'Bean',
      'Bok Choy',
      'Bell Pepper',
    ],
    C: [
      'Carrot',
      'Celery',
      'Corn',
      'Cabbage',
      'Cauliflower',
      'Cucumber',
      'Chili Pepper',
    ],
    D: ['Daikon'],
    E: ['Eggplant', 'Endive', 'Edamame'],
    F: ['Fennel'],
    G: ['Garlic', 'Green Bean', 'Ginger'],
    H: ['Horseradish'],
    I: [],
    J: ['Jalapeno', 'Jicama'],
    K: ['Kale', 'Kohlrabi'],
    L: ['Leek', 'Lettuce', 'Lima Bean'],
    M: ['Mushroom'],
    N: ['Napa Cabbage'],
    O: ['Onion', 'Okra'],
    P: ['Potato', 'Pea', 'Parsnip', 'Pepper', 'Pumpkin'],
    Q: [],
    R: ['Radish', 'Rhubarb', 'Rutabaga'],
    S: ['Spinach', 'Squash', 'Sweet Potato', 'Scallion', 'Snow Pea', 'Shallot'],
    T: ['Turnip', 'Tomato', 'Taro'],
    U: [],
    V: [],
    W: ['Watercress', 'Wasabi'],
    X: [],
    Y: ['Yam'],
    Z: ['Zucchini'],
  },
  Drink: {
    A: ['Apple Juice', 'Ale', 'Americano'],
    B: ['Beer', 'Bourbon', 'Brandy'],
    C: [
      'Coffee',
      'Cola',
      'Champagne',
      'Cider',
      'Cappuccino',
      'Chai',
      'Coconut Water',
      'Cocktail',
    ],
    D: ['Daiquiri'],
    E: ['Espresso', 'Eggnog', 'Energy Drink'],
    F: ['Frappe'],
    G: ['Ginger Ale', 'Ginger Beer', 'Green Tea', 'Grog'],
    H: ['Hot Chocolate', 'Herbal Tea'],
    I: ['Iced Tea', 'Irish Coffee'],
    J: ['Juice'],
    K: ['Kombucha'],
    L: ['Lemonade', 'Latte', 'Limeade', 'Liqueur'],
    M: ['Milkshake', 'Martini', 'Margarita', 'Mocha', 'Mead', 'Mojito', 'Milk'],
    N: [],
    O: ['Orange Juice'],
    P: ['Pepsi', 'Punch', 'Prosecco'],
    Q: [],
    R: ['Root Beer', 'Rum', 'Red Wine', 'Rose Wine'],
    S: ['Smoothie', 'Soda', 'Sake', 'Sangria', 'Sprite', 'Sparkling Water'],
    T: ['Tea', 'Tequila', 'Tonic Water'],
    U: [],
    V: ['Vodka'],
    W: ['Water', 'Wine', 'Whiskey', 'White Wine'],
    X: [],
    Y: ['Yakult', 'Yerba Mate'],
    Z: [],
  },
  'Clothing Item': {
    A: ['Anorak', 'Apron'],
    B: [
      'Blouse',
      'Boots',
      'Belt',
      'Blazer',
      'Bra',
      'Beanie',
      'Bikini',
      'Bow Tie',
    ],
    C: ['Coat', 'Cap', 'Cardigan', 'Crop Top', 'Corset'],
    D: ['Dress', 'Denim Jacket'],
    E: ['Earrings'],
    F: ['Flannel'],
    G: ['Gloves', 'Gown', 'Glasses'],
    H: ['Hoodie', 'Hat', 'High Heels'],
    I: [],
    J: ['Jacket', 'Jeans', 'Jumpsuit', 'Jersey'],
    K: ['Kimono', 'Kilt'],
    L: ['Leggings', 'Loafers'],
    M: ['Mittens', 'Moccasins', 'Miniskirt'],
    N: ['Necklace', 'Nightgown'],
    O: ['Overalls', 'Overcoat'],
    P: ['Pants', 'Polo', 'Parka', 'Pajamas', 'Poncho'],
    Q: [],
    R: ['Robe', 'Raincoat', 'Ring'],
    S: [
      'Shirt',
      'Shorts',
      'Skirt',
      'Scarf',
      'Sneakers',
      'Sandals',
      'Sweater',
      'Suit',
      'Socks',
      'Sunglasses',
    ],
    T: [
      'T-Shirt',
      'Trousers',
      'Tuxedo',
      'Tank Top',
      'Tie',
      'Trench Coat',
      'Tights',
    ],
    U: ['Underwear', 'Uniform'],
    V: ['Vest'],
    W: ['Windbreaker', 'Watch'],
    X: [],
    Y: [],
    Z: [],
  },
  'Household Object': {
    A: ['Alarm Clock', 'Air Conditioner'],
    B: ['Blanket', 'Broom', 'Bucket', 'Basket', 'Bookshelf', 'Blender', 'Bowl'],
    C: [
      'Chair',
      'Clock',
      'Couch',
      'Curtain',
      'Candle',
      'Cushion',
      'Cup',
      'Cabinet',
    ],
    D: ['Desk', 'Doorbell', 'Dishwasher', 'Drawer', 'Dryer'],
    E: [],
    F: ['Fan', 'Fork', 'Frame', 'Freezer', 'Fridge'],
    G: ['Glass', 'Garden Hose'],
    H: ['Hanger', 'Heater'],
    I: ['Iron', 'Ironing Board'],
    J: ['Jar'],
    K: ['Kettle', 'Knife', 'Key'],
    L: ['Lamp', 'Laundry Basket', 'Lock'],
    M: ['Mirror', 'Mop', 'Mat', 'Microwave', 'Mug'],
    N: ['Napkin'],
    O: ['Oven'],
    P: ['Pillow', 'Pan', 'Plate', 'Pot', 'Picture Frame'],
    Q: ['Quilt'],
    R: ['Rug', 'Remote Control', 'Refrigerator'],
    S: ['Sofa', 'Sink', 'Shelf', 'Stove', 'Sponge', 'Scissors', 'Shower'],
    T: ['Table', 'Towel', 'Toaster', 'Trash Can', 'Tissue Box', 'Thermostat'],
    U: ['Umbrella'],
    V: ['Vacuum', 'Vase'],
    W: ['Washing Machine', 'Window', 'Wastebasket'],
    X: [],
    Y: [],
    Z: [],
  },
  'Boy Name': {
    A: [
      'Adam',
      'Andrew',
      'Alexander',
      'Anthony',
      'Aaron',
      'Austin',
      'Aiden',
      'Asher',
      'Axel',
    ],
    B: [
      'Benjamin',
      'Brandon',
      'Brian',
      'Blake',
      'Bradley',
      'Brody',
      'Brooks',
      'Beckett',
    ],
    C: [
      'Christopher',
      'Charles',
      'Caleb',
      'Cameron',
      'Carter',
      'Christian',
      'Connor',
      'Chase',
      'Cole',
    ],
    D: [
      'Daniel',
      'David',
      'Dylan',
      'Dominic',
      'Dean',
      'Derek',
      'Damian',
      'Declan',
      'Diego',
    ],
    E: [
      'Ethan',
      'Elijah',
      'Evan',
      'Edward',
      'Eric',
      'Emilio',
      'Easton',
      'Emmett',
    ],
    F: ['Felix', 'Finn', 'Frank', 'Frederick', 'Fabian', 'Fisher', 'Flynn'],
    G: [
      'Gabriel',
      'George',
      'Gavin',
      'Grant',
      'Grayson',
      'Greyson',
      'Griffin',
      'Graham',
    ],
    H: [
      'Henry',
      'Hunter',
      'Harrison',
      'Harvey',
      'Hayden',
      'Hector',
      'Hugo',
      'Heath',
    ],
    I: ['Isaac', 'Ian', 'Ivan', 'Isaiah'],
    J: [
      'James',
      'John',
      'Joseph',
      'Jacob',
      'Jack',
      'Jason',
      'Joshua',
      'Julian',
      'Jasper',
      'Jace',
    ],
    K: ['Kevin', 'Kyle', 'Kenneth', 'Knox', 'Kai', 'Kingston', 'Kaleb'],
    L: [
      'Leonardo',
      'Lucas',
      'Logan',
      'Liam',
      'Luke',
      'Leo',
      'Landon',
      'Lawrence',
    ],
    M: [
      'Matthew',
      'Michael',
      'Mason',
      'Marcus',
      'Max',
      'Miles',
      'Milo',
      'Martin',
      'Maverick',
    ],
    N: ['Nathan', 'Noah', 'Nicholas', 'Nolan', 'Nash', 'Neil'],
    O: ['Oliver', 'Oscar', 'Owen', 'Omar'],
    P: ['Patrick', 'Peter', 'Philip', 'Parker', 'Preston', 'Paul', 'Phoenix'],
    Q: ['Quinn', 'Quentin'],
    R: [
      'Ryan',
      'Robert',
      'Richard',
      'Raymond',
      'Riley',
      'Roman',
      'Rowan',
      'Reid',
      'Rhett',
    ],
    S: [
      'Samuel',
      'Sebastian',
      'Simon',
      'Sean',
      'Spencer',
      'Silas',
      'Sawyer',
      'Santiago',
    ],
    T: [
      'Thomas',
      'Tyler',
      'Theodore',
      'Timothy',
      'Tristan',
      'Tucker',
      'Tobias',
      'Tate',
    ],
    U: ['Ulysses'],
    V: ['Victor', 'Vincent', 'Valentino'],
    W: ['William', 'Wyatt', 'Wesley', 'Walter', 'Warren', 'Weston'],
    X: ['Xavier', 'Xander'],
    Y: ['Yusuf'],
    Z: ['Zachary', 'Zander', 'Zane'],
  },
  'Girl Name': {
    A: [
      'Amelia',
      'Ava',
      'Aria',
      'Abigail',
      'Aurora',
      'Audrey',
      'Alice',
      'Adeline',
      'Athena',
      'Anna',
    ],
    B: [
      'Bella',
      'Brooklyn',
      'Brielle',
      'Brianna',
      'Bailey',
      'Bianca',
      'Brooke',
      'Beatrice',
    ],
    C: [
      'Charlotte',
      'Chloe',
      'Claire',
      'Caroline',
      'Camilla',
      'Clara',
      'Cora',
      'Catherine',
      'Celeste',
    ],
    D: ['Daisy', 'Delilah', 'Diana', 'Dorothy'],
    E: [
      'Emma',
      'Emily',
      'Eleanor',
      'Elizabeth',
      'Ella',
      'Eva',
      'Elena',
      'Eloise',
      'Evelyn',
    ],
    F: ['Faith', 'Fiona', 'Florence', 'Freya', 'Francesca', 'Felicity'],
    G: [
      'Grace',
      'Gabriella',
      'Gemma',
      'Georgia',
      'Giselle',
      'Gloria',
      'Genevieve',
    ],
    H: ['Harper', 'Hazel', 'Hannah', 'Hailey', 'Hope', 'Helena', 'Holly'],
    I: ['Isabella', 'Ivy', 'Iris', 'Isla', 'Imogen'],
    J: [
      'Julia',
      'Jasmine',
      'Josephine',
      'Jessica',
      'Jade',
      'Juliana',
      'Jane',
      'Joy',
      'Jocelyn',
    ],
    K: ['Kennedy', 'Katherine', 'Khloe', 'Kylie', 'Kira'],
    L: [
      'Luna',
      'Lily',
      'Layla',
      'Lucy',
      'Leah',
      'Lila',
      'Lydia',
      'Lola',
      'Lucia',
    ],
    M: [
      'Mia',
      'Maya',
      'Madeline',
      'Melody',
      'Morgan',
      'Matilda',
      'Margot',
      'Mila',
      'Molly',
    ],
    N: ['Nora', 'Natalie', 'Naomi', 'Nicole', 'Nadia', 'Noelle', 'Nina'],
    O: ['Olivia', 'Ophelia'],
    P: ['Penelope', 'Piper', 'Paige', 'Phoebe', 'Presley', 'Priscilla'],
    Q: ['Quinn'],
    R: [
      'Riley',
      'Ruby',
      'Rose',
      'Reagan',
      'Rosalie',
      'Raelynn',
      'Rebecca',
      'Rhea',
    ],
    S: [
      'Sophia',
      'Scarlett',
      'Stella',
      'Savannah',
      'Sadie',
      'Sarah',
      'Sienna',
      'Skylar',
      'Serena',
    ],
    T: ['Trinity', 'Taylor', 'Thea', 'Tessa'],
    U: ['Uma'],
    V: ['Violet', 'Victoria', 'Valentina', 'Vivian', 'Vera', 'Vanessa'],
    W: ['Willow', 'Wren', 'Winter'],
    X: ['Ximena'],
    Y: ['Yasmine'],
    Z: ['Zoe', 'Zara', 'Zelda'],
  },
  Food: {
    A: ['Avocado Toast', 'Apple Pie', 'Alfredo'],
    B: ['Burger', 'Burrito', 'Bagel', 'Bacon', 'Biryani', 'Bruschetta', 'BLT'],
    C: [
      'Curry',
      'Crepe',
      'Calzone',
      'Chili',
      'Chicken',
      'Croissant',
      'Ceviche',
    ],
    D: ['Dim Sum', 'Dumpling'],
    E: ['Enchilada', 'Egg Roll'],
    F: [
      'Fish and Chips',
      'Fajita',
      'Focaccia',
      'French Fries',
      'Fondue',
      'Fried Rice',
    ],
    G: ['Goulash', 'Gyro', 'Gnocchi', 'Granola', 'Guacamole', 'Grilled Cheese'],
    H: ['Hummus', 'Hot Dog', 'Hamburger', 'Hash Brown'],
    I: [],
    J: ['Jambalaya'],
    K: ['Kebab', 'Kimchi'],
    L: ['Lasagna', 'Lobster Roll'],
    M: ['Mac and Cheese', 'Meatball', 'Miso Soup', 'Moussaka'],
    N: ['Nachos', 'Naan', 'Noodles', 'Nuggets'],
    O: ['Omelette', 'Onion Rings'],
    P: [
      'Pizza',
      'Pancake',
      'Pasta',
      'Pho',
      'Pretzel',
      'Paella',
      'Pad Thai',
      'Pot Pie',
    ],
    Q: ['Quesadilla', 'Quiche'],
    R: ['Ramen', 'Ravioli', 'Risotto', 'Ratatouille', 'Rib Eye'],
    S: [
      'Sushi',
      'Steak',
      'Sandwich',
      'Salad',
      'Soup',
      'Samosa',
      'Shawarma',
      'Spring Roll',
    ],
    T: ['Taco', 'Tempura', 'Tikka Masala', 'Toast', 'Tofu', 'Tortilla'],
    U: ['Udon'],
    V: [],
    W: ['Waffle', 'Wrap', 'Wonton', 'Wings'],
    X: [],
    Y: ['Yakitori', 'Yogurt'],
    Z: ['Ziti'],
  },
  'Car Brand': {
    A: ['Audi', 'Acura', 'Alfa Romeo', 'Aston Martin'],
    B: ['BMW', 'Bentley', 'Bugatti', 'Buick'],
    C: ['Chevrolet', 'Cadillac', 'Chrysler', 'Citroen'],
    D: ['Dodge', 'Ducati', 'Daihatsu'],
    E: [],
    F: ['Ford', 'Ferrari', 'Fiat'],
    G: ['GMC', 'Genesis'],
    H: ['Honda', 'Hyundai', 'Hummer'],
    I: ['Infiniti', 'Isuzu'],
    J: ['Jeep', 'Jaguar'],
    K: ['Kia', 'Koenigsegg'],
    L: ['Lexus', 'Lamborghini', 'Land Rover', 'Lincoln', 'Lotus'],
    M: ['Mercedes', 'Mazda', 'Maserati', 'McLaren', 'Mitsubishi', 'Mini'],
    N: ['Nissan'],
    O: ['Opel'],
    P: ['Porsche', 'Peugeot', 'Pontiac'],
    Q: [],
    R: ['Rolls Royce', 'Renault', 'Ram', 'Rivian'],
    S: ['Subaru', 'Suzuki', 'Skoda', 'Smart'],
    T: ['Toyota', 'Tesla', 'TVR'],
    U: [],
    V: ['Volkswagen', 'Volvo', 'Vauxhall'],
    W: [],
    X: [],
    Y: [],
    Z: [],
  },
  'Video Game': {
    A: [
      'Apex Legends',
      'Assassins Creed',
      'Among Us',
      'Animal Crossing',
      'Anthem',
    ],
    B: ['Battlefield', 'Bioshock', 'Borderlands', 'Breath of the Wild'],
    C: [
      'Call of Duty',
      'Counter Strike',
      'Cyberpunk',
      'Civilization',
      'Crash Bandicoot',
      'Cuphead',
      'Celeste',
    ],
    D: [
      'Destiny',
      'Dark Souls',
      'Doom',
      'Diablo',
      'Dead Space',
      'Detroit Become Human',
      'Donkey Kong',
    ],
    E: ['Elder Scrolls', 'Elden Ring'],
    F: ['Fallout', 'FIFA', 'Fortnite', 'Final Fantasy', 'Far Cry', 'Fable'],
    G: [
      'GTA',
      'God of War',
      'Gears of War',
      'Genshin Impact',
      'Ghost of Tsushima',
    ],
    H: ['Halo', 'Half-Life', 'Hitman', 'Horizon Zero Dawn', 'Hollow Knight'],
    I: [],
    J: ['Just Cause', 'Just Dance'],
    K: ['Kingdom Hearts', 'Kirby'],
    L: ['League of Legends', 'Left 4 Dead', 'Little Big Planet'],
    M: [
      'Minecraft',
      'Mario',
      'Mass Effect',
      'Metal Gear Solid',
      'Mortal Kombat',
      'Monster Hunter',
    ],
    N: ['No Mans Sky', 'NieR Automata'],
    O: ['Overwatch', 'Outlast'],
    P: ['Pokemon', 'Portal', 'Persona'],
    Q: [],
    R: [
      'Red Dead Redemption',
      'Resident Evil',
      'Rocket League',
      'Roblox',
      'Raft',
      'Rust',
    ],
    S: [
      'Skyrim',
      'Sekiro',
      'Sonic',
      'Spider-Man',
      'Stardew Valley',
      'Splinter Cell',
      'Sims',
      'Street Fighter',
      'Smash Bros',
      'Subnautica',
    ],
    T: ['Tetris', 'The Witcher', 'Tomb Raider', 'Tekken', 'Terraria'],
    U: ['Uncharted', 'Undertale'],
    V: ['Valorant'],
    W: ['World of Warcraft', 'Watch Dogs', 'Wii Sports'],
    X: ['XCOM', 'Xenoblade'],
    Y: [],
    Z: ['Zelda'],
  },
  Language: {
    A: ['Arabic', 'Albanian', 'Amharic', 'Armenian', 'Afrikaans'],
    B: ['Bengali', 'Bulgarian', 'Basque', 'Bosnian'],
    C: ['Chinese', 'Czech', 'Croatian', 'Catalan', 'Cantonese'],
    D: ['Dutch', 'Danish', 'Dari'],
    E: ['English', 'Estonian', 'Esperanto'],
    F: ['French', 'Finnish', 'Farsi', 'Filipino', 'Flemish'],
    G: ['German', 'Greek', 'Georgian', 'Gaelic', 'Galician', 'Gujarati'],
    H: ['Hindi', 'Hebrew', 'Hungarian', 'Haitian Creole', 'Hawaiian'],
    I: ['Italian', 'Indonesian', 'Icelandic', 'Irish'],
    J: ['Japanese', 'Javanese'],
    K: ['Korean', 'Kurdish', 'Kazakh', 'Khmer', 'Kannada'],
    L: ['Latin', 'Latvian', 'Lithuanian', 'Lao'],
    M: ['Mandarin', 'Malay', 'Mongolian', 'Malayalam', 'Maltese', 'Macedonian'],
    N: ['Nepali', 'Norwegian'],
    O: [],
    P: ['Portuguese', 'Polish', 'Punjabi', 'Persian', 'Pashto'],
    Q: ['Quechua'],
    R: ['Russian', 'Romanian', 'Romani'],
    S: [
      'Spanish',
      'Swedish',
      'Serbian',
      'Slovak',
      'Slovenian',
      'Swahili',
      'Somali',
      'Sindhi',
      'Samoan',
    ],
    T: ['Turkish', 'Thai', 'Tamil', 'Telugu', 'Tibetan', 'Tagalog'],
    U: ['Ukrainian', 'Urdu', 'Uzbek'],
    V: ['Vietnamese'],
    W: ['Welsh'],
    X: ['Xhosa'],
    Y: ['Yiddish', 'Yoruba'],
    Z: ['Zulu'],
  },
  Tool: {
    A: ['Axe', 'Awl', 'Allen Key', 'Angle Grinder'],
    B: ['Bolt Cutter', 'Blowtorch', 'Bench Vice'],
    C: ['Chisel', 'Clamp', 'Compass', 'Crowbar', 'Caliper', 'Chain Saw'],
    D: ['Drill', 'Duct Tape'],
    E: [],
    F: ['File'],
    G: ['Grinder', 'Glue Gun'],
    H: ['Hammer', 'Hacksaw', 'Hex Key', 'Hand Saw', 'Hoe'],
    I: [],
    J: ['Jack', 'Jigsaw'],
    K: ['Knife'],
    L: ['Level', 'Lathe', 'Ladder'],
    M: ['Mallet', 'Measuring Tape', 'Multimeter'],
    N: ['Nail Gun', 'Needle Nose Pliers', 'Nut Driver'],
    O: [],
    P: ['Pliers', 'Pickaxe', 'Putty Knife', 'Power Drill', 'Plane'],
    Q: [],
    R: ['Ratchet', 'Rasp', 'Router', 'Ruler', 'Rivet Gun'],
    S: [
      'Saw',
      'Screwdriver',
      'Sandpaper',
      'Sledgehammer',
      'Socket Wrench',
      'Shovel',
      'Staple Gun',
      'Sander',
    ],
    T: ['Tape Measure', 'Trowel', 'T-Square', 'Torque Wrench'],
    U: [],
    V: ['Vise', 'Voltage Tester'],
    W: ['Wrench', 'Wire Stripper', 'Wire Cutter', 'Wheelbarrow'],
    X: [],
    Y: [],
    Z: [],
  },
  'Musical Instrument': {
    A: ['Accordion', 'Acoustic Guitar'],
    B: ['Banjo', 'Bass', 'Bongos', 'Bugle', 'Bagpipes', 'Bassoon', 'Bell'],
    C: ['Cello', 'Clarinet', 'Cymbals', 'Castanets', 'Conga'],
    D: ['Drums', 'Didgeridoo', 'Dulcimer'],
    E: ['Electric Guitar', 'English Horn'],
    F: ['Flute', 'French Horn', 'Fiddle'],
    G: ['Guitar', 'Glockenspiel', 'Gong'],
    H: ['Harp', 'Harmonica', 'Horn'],
    I: [],
    J: [],
    K: ['Kazoo', 'Kalimba', 'Keyboard'],
    L: ['Lute', 'Lyre'],
    M: ['Mandolin', 'Maracas', 'Melodica'],
    N: [],
    O: ['Oboe', 'Organ', 'Ocarina'],
    P: ['Piano', 'Piccolo', 'Panpipes'],
    Q: [],
    R: ['Recorder'],
    S: ['Saxophone', 'Sitar', 'Snare Drum', 'Steel Drum', 'Synthesizer'],
    T: ['Trumpet', 'Trombone', 'Tuba', 'Tambourine', 'Triangle', 'Timpani'],
    U: ['Ukulele'],
    V: ['Violin', 'Viola', 'Vibraphone'],
    W: ['Whistle'],
    X: ['Xylophone'],
    Y: [],
    Z: ['Zither'],
  },
  'Programming Language': {
    A: ['Assembly', 'Ada', 'ActionScript', 'ABAP', 'AppleScript', 'AWK'],
    B: ['BASIC', 'Bash'],
    C: ['C', 'C++', 'C#', 'COBOL', 'Clojure', 'CoffeeScript', 'Crystal'],
    D: ['Dart', 'Delphi'],
    E: ['Elixir', 'Erlang', 'Elm'],
    F: ['Fortran', 'F#'],
    G: ['Go', 'Groovy', 'GDScript'],
    H: ['Haskell', 'HTML', 'Hack'],
    I: [],
    J: ['Java', 'JavaScript', 'JSON', 'Julia', 'Jupyter'],
    K: ['Kotlin', 'Kubernetes'],
    L: ['Lua', 'Lisp', 'Logo'],
    M: ['MATLAB', 'Markdown'],
    N: ['Nim'],
    O: ['Objective-C', 'OCaml'],
    P: ['Python', 'PHP', 'Perl', 'Pascal', 'PowerShell', 'Prolog'],
    Q: [],
    R: ['R', 'Ruby', 'Rust', 'Racket'],
    S: ['Swift', 'SQL', 'Scala', 'Scratch', 'Scheme', 'Solidity', 'Shell'],
    T: ['TypeScript', 'Tcl', 'Turing'],
    U: [],
    V: ['Verilog', 'VHDL', 'VBA', 'Visual Basic'],
    W: ['WebAssembly'],
    X: ['XML', 'XSLT'],
    Y: ['YAML'],
    Z: ['Zig'],
  },
  'Chemical Element': {
    A: ['Argon', 'Aluminum', 'Arsenic', 'Americium', 'Antimony', 'Astatine'],
    B: ['Boron', 'Barium', 'Bismuth', 'Bromine', 'Beryllium', 'Berkelium'],
    C: [
      'Carbon',
      'Calcium',
      'Chlorine',
      'Chromium',
      'Cobalt',
      'Copper',
      'Cesium',
      'Cerium',
      'Curium',
    ],
    D: ['Dubnium', 'Dysprosium'],
    E: ['Einsteinium', 'Erbium', 'Europium'],
    F: ['Fluorine', 'Fermium', 'Francium'],
    G: ['Gold', 'Gallium', 'Germanium', 'Gadolinium'],
    H: ['Hydrogen', 'Helium', 'Hafnium', 'Holmium', 'Hassium'],
    I: ['Iron', 'Iodine', 'Iridium', 'Indium'],
    J: [],
    K: ['Krypton'],
    L: [
      'Lithium',
      'Lead',
      'Lanthanum',
      'Lawrencium',
      'Lutetium',
      'Livermorium',
    ],
    M: [
      'Magnesium',
      'Manganese',
      'Mercury',
      'Molybdenum',
      'Mendelevium',
      'Moscovium',
    ],
    N: [
      'Nitrogen',
      'Nickel',
      'Neon',
      'Niobium',
      'Nobelium',
      'Neptunium',
      'Neodymium',
    ],
    O: ['Oxygen', 'Osmium', 'Oganesson'],
    P: [
      'Phosphorus',
      'Platinum',
      'Potassium',
      'Palladium',
      'Plutonium',
      'Polonium',
      'Praseodymium',
      'Promethium',
      'Protactinium',
    ],
    Q: [],
    R: [
      'Radium',
      'Radon',
      'Rhenium',
      'Rhodium',
      'Rubidium',
      'Ruthenium',
      'Rutherfordium',
      'Roentgenium',
    ],
    S: [
      'Silicon',
      'Silver',
      'Sodium',
      'Sulfur',
      'Scandium',
      'Selenium',
      'Strontium',
      'Samarium',
      'Seaborgium',
    ],
    T: [
      'Tin',
      'Titanium',
      'Tungsten',
      'Thallium',
      'Thorium',
      'Thulium',
      'Tennessine',
      'Terbium',
      'Technetium',
    ],
    U: ['Uranium', 'Ununoctium'],
    V: ['Vanadium'],
    W: [],
    X: ['Xenon'],
    Y: ['Yttrium', 'Ytterbium'],
    Z: ['Zinc', 'Zirconium'],
  },
  Superhero: {
    A: ['Aquaman', 'Ant-Man', 'Arrow'],
    B: ['Batman', 'Black Panther', 'Black Widow', 'Batgirl'],
    C: ['Captain America', 'Catwoman', 'Cyclops', 'Captain Marvel'],
    D: ['Daredevil', 'Deadpool', 'Doctor Strange'],
    E: ['Elektra'],
    F: ['Flash', 'Falcon', 'Fantastic Four'],
    G: ['Green Lantern', 'Gambit', 'Groot', 'Green Arrow', 'Gamora'],
    H: ['Hulk', 'Hawkeye', 'Hellboy'],
    I: ['Iron Man', 'Invisible Woman', 'Iron Fist'],
    J: ['Jean Grey', 'Justice League'],
    K: [],
    L: ['Loki'],
    M: ['Magneto', 'Mystique'],
    N: ['Nightcrawler', 'Nick Fury'],
    O: [],
    P: ['Power Girl', 'Punisher', 'Professor X'],
    Q: [],
    R: ['Robin', 'Rogue'],
    S: [
      'Superman',
      'Spider-Man',
      'Supergirl',
      'She-Hulk',
      'Silver Surfer',
      'Storm',
      'Scarlet Witch',
      'Shazam',
    ],
    T: ['Thor', 'Thanos'],
    U: [],
    V: ['Vision', 'Venom'],
    W: ['Wonder Woman', 'Wolverine', 'Wasp', 'War Machine'],
    X: ['X-Men'],
    Y: [],
    Z: ['Zatanna'],
  },
  Furniture: {
    A: ['Armchair', 'Armoire'],
    B: [
      'Bed',
      'Bookshelf',
      'Bench',
      'Bean Bag',
      'Bureau',
      'Buffet',
      'Bunk Bed',
    ],
    C: [
      'Chair',
      'Couch',
      'Cabinet',
      'Coffee Table',
      'Chest',
      'Credenza',
      'Console',
      'Crib',
    ],
    D: ['Desk', 'Dresser', 'Dining Table', 'Daybed', 'Divan'],
    E: ['End Table', 'Entertainment Center', 'Etagere'],
    F: ['Futon', 'Footstool', 'Filing Cabinet'],
    G: [],
    H: ['Hammock', 'Headboard', 'Hutch', 'High Chair', 'Hall Table'],
    I: [],
    J: [],
    K: ['Kitchen Island'],
    L: ['Loveseat', 'Lamp Table', 'Lounge Chair'],
    M: ['Mirror', 'Magazine Rack', 'Mattress'],
    N: ['Nightstand', 'Nesting Tables'],
    O: ['Ottoman', 'Office Chair'],
    P: ['Pantry', 'Pedestal Table', 'Patio Chair', 'Pouf'],
    Q: [],
    R: ['Recliner', 'Rocking Chair', 'Room Divider', 'Rug'],
    S: [
      'Sofa',
      'Shelf',
      'Stool',
      'Sideboard',
      'Sectional',
      'Stand',
      'Storage Bench',
    ],
    T: ['Table', 'TV Stand', 'Trunk'],
    U: [],
    V: ['Vanity'],
    W: ['Wardrobe', 'Writing Desk', 'Wine Rack', 'Wingback Chair'],
    X: [],
    Y: [],
    Z: [],
  },
  'School Subject': {
    A: [
      'Algebra',
      'Art',
      'Anatomy',
      'Anthropology',
      'Astronomy',
      'Agriculture',
      'Accounting',
    ],
    B: ['Biology', 'Botany', 'Business'],
    C: [
      'Chemistry',
      'Calculus',
      'Computer Science',
      'Civics',
      'Creative Writing',
    ],
    D: ['Drama', 'Design'],
    E: ['English', 'Economics', 'Engineering', 'Ethics', 'Ecology'],
    F: ['French'],
    G: ['Geography', 'Geology', 'German', 'Geometry', 'Gym', 'Graphic Design'],
    H: ['History', 'Health', 'Home Economics'],
    I: [],
    J: ['Journalism'],
    K: [],
    L: ['Literature', 'Latin', 'Law', 'Linguistics', 'Logic'],
    M: ['Mathematics', 'Music', 'Marine Biology', 'Meteorology', 'Marketing'],
    N: ['Nutrition'],
    O: [],
    P: [
      'Physics',
      'Philosophy',
      'Psychology',
      'Physical Education',
      'Political Science',
      'Photography',
    ],
    Q: [],
    R: ['Reading', 'Religion', 'Robotics'],
    S: ['Science', 'Sociology', 'Spanish', 'Statistics', 'Swimming'],
    T: ['Trigonometry', 'Theater', 'Technology'],
    U: [],
    V: [],
    W: ['Writing', 'Woodworking', 'World History'],
    X: [],
    Y: [],
    Z: ['Zoology'],
  },
};

export function getAnswersForCategory(
  categoryName: string,
  letter: string,
): string[] {
  const cat = ANSWERS[categoryName];
  if (!cat) return [];
  return cat[letter.toUpperCase()] || [];
}

export function getCategoriesWithAnswers(): string[] {
  return Object.keys(ANSWERS);
}
